# Generated by Django 3.1.7 on 2021-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='test',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
