# Generated by Django 3.1.7 on 2021-07-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0002_location_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Cases',
        ),
        migrations.AddField(
            model_name='location',
            name='Cases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.cases'),
            preserve_default=False,
        ),
    ]
