# Generated by Django 3.1.7 on 2021-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0003_auto_20210705_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Cases',
        ),
        migrations.AddField(
            model_name='location',
            name='Cases',
            field=models.ManyToManyField(blank=True, to='covidtracker.Cases'),
        ),
    ]
