# Generated by Django 3.1.7 on 2021-07-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0004_auto_20210705_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zambia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western')], max_length=20)),
                ('casesToday', models.CharField(blank=True, max_length=30)),
                ('casesTotal', models.CharField(blank=True, max_length=30)),
                ('testsToday', models.CharField(blank=True, max_length=30)),
                ('testsTotal', models.CharField(blank=True, max_length=30)),
                ('recoveriesToday', models.CharField(blank=True, max_length=30)),
                ('recoveriesTotal', models.CharField(blank=True, max_length=30)),
                ('deathsToday', models.CharField(blank=True, max_length=30)),
                ('deathsTotal', models.CharField(blank=True, max_length=30)),
                ('VaccinationToday', models.CharField(blank=True, max_length=30)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtracker.date')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western')], max_length=20)),
                ('cases', models.CharField(blank=True, max_length=30)),
                ('deaths', models.CharField(blank=True, max_length=30)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtracker.date')),
            ],
        ),
    ]
