# Generated by Django 3.1.7 on 2021-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0006_auto_20210706_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Cases',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Deaths',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Recoveries',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Tests',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Vaccinated',
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western'), ('Muchinga', 'Muchinga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='zambia',
            name='name',
            field=models.CharField(blank=True, choices=[('Zambia', 'Zambia'), ('Lusaka', 'Lusaka'), ('Copperbelt', 'Copperbelt'), ('Luapula', 'Luapula'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Northern', 'Northern'), ('Western', 'Western'), ('North-Western', 'North-Western'), ('Muchinga', 'Muchinga')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Deaths',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Recoveries',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.DeleteModel(
            name='Vaccinations',
        ),
    ]
